### ISSUE TITLE
README example contains internal Adobe link

### ISSUE THREAD

**Issue by filmaj** [adobe/eventhub-akka-connector#1]
> To materialize it into a IEventProcessor it has to be materialized and run, like an Akka streams source( see the example for details).

The example points to this link: https://git.corp.adobe.com/proton/eventhub-akka-connector/blob/master/src/main/java/com/adobe/proton/eventhub/examples/SingleProcessorExample.java

... which is not publicly viewable.

**Comment by pallavL01** [comment]
@filmaj thanks for pointing out the issue. I have updated the link to the public URL.
